-- Create user_positions table
-- This table tracks user investment positions in different tiers

CREATE TABLE IF NOT EXISTS public.user_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    tier_id BIGINT NOT NULL REFERENCES public.investment_tiers(id) ON DELETE RESTRICT,
    amount DECIMAL(20,8) NOT NULL DEFAULT 0,
    currency VARCHAR(10) NOT NULL DEFAULT 'USDT',
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'matured', 'closed')),
    opened_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    matures_at TIMESTAMP WITH TIME ZONE,
    closed_at TIMESTAMP WITH TIME ZONE,
    
    -- Trading position details
    symbol VARCHAR(20),
    position_type VARCHAR(10) CHECK (position_type IN ('long', 'short')),
    entry_price DECIMAL(20,8),
    current_price DECIMAL(20,8),
    quantity DECIMAL(20,8),
    unrealized_pnl DECIMAL(20,8) DEFAULT 0,
    
    -- ROI tracking
    accrued_roi DECIMAL(20,8) DEFAULT 0,
    last_roi_calculation TIMESTAMP WITH TIME ZONE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_user_positions_user_id ON public.user_positions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_positions_tier_id ON public.user_positions(tier_id);
CREATE INDEX IF NOT EXISTS idx_user_positions_status ON public.user_positions(status);
CREATE INDEX IF NOT EXISTS idx_user_positions_matures_at ON public.user_positions(matures_at);
CREATE INDEX IF NOT EXISTS idx_user_positions_user_status ON public.user_positions(user_id, status);

-- Create updated_at trigger
DROP TRIGGER IF EXISTS handle_user_positions_updated_at ON public.user_positions;
CREATE TRIGGER handle_user_positions_updated_at
    BEFORE UPDATE ON public.user_positions
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Function to calculate maturity date based on tier
CREATE OR REPLACE FUNCTION public.calculate_position_maturity(p_tier_id BIGINT)
RETURNS TIMESTAMP WITH TIME ZONE AS $$
DECLARE
    tier_period INTEGER;
BEGIN
    SELECT investment_period_days INTO tier_period
    FROM public.investment_tiers
    WHERE id = p_tier_id;
    
    IF tier_period IS NULL THEN
        RETURN NOW() + INTERVAL '30 days'; -- Default fallback
    END IF;
    
    RETURN NOW() + (tier_period || ' days')::INTERVAL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to auto-set maturity date
CREATE OR REPLACE FUNCTION public.set_position_maturity()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.matures_at IS NULL AND NEW.tier_id IS NOT NULL THEN
        NEW.matures_at = public.calculate_position_maturity(NEW.tier_id);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_set_position_maturity ON public.user_positions;
CREATE TRIGGER trigger_set_position_maturity
    BEFORE INSERT ON public.user_positions
    FOR EACH ROW
    EXECUTE FUNCTION public.set_position_maturity();

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_positions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_positions TO service_role;

-- Grant execute permissions on functions
GRANT EXECUTE ON FUNCTION public.calculate_position_maturity TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_position_maturity TO service_role;
GRANT EXECUTE ON FUNCTION public.set_position_maturity TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_position_maturity TO service_role;
