-- Create investment_tiers table
-- This table defines the different investment tiers available in the platform

CREATE TABLE IF NOT EXISTS public.investment_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    min_amount DECIMAL(20,8) NOT NULL DEFAULT 0,
    max_amount DECIMAL(20,8), -- NULL means unlimited
    investment_period_days INTEGER NOT NULL DEFAULT 30,
    daily_roi DECIMAL(10,8) NOT NULL DEFAULT 0.005, -- Daily ROI as decimal (0.005 = 0.5%)
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    features JSONB, -- Array of features for this tier
    allocation_mix JSONB, -- Asset allocation percentages (e.g., {"BTC": 40, "ETH": 30, "USDT": 30})
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_investment_tiers_active_sort ON public.investment_tiers(is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_investment_tiers_min_amount ON public.investment_tiers(min_amount);

-- Insert default tier data
INSERT INTO public.investment_tiers (name, description, min_amount, max_amount, investment_period_days, daily_roi, sort_order, features, allocation_mix) VALUES
(
    'Tier 1',
    'Entry-level investment tier with competitive returns.',
    150.00,
    1000.00,
    30,
    0.005, -- 0.5% daily
    1,
    '["Basic trading signals", "Email support", "Daily ROI payouts"]',
    '{"BTC": 40, "ETH": 30, "USDT": 30}'
),
(
    'Tier 2',
    'Intermediate tier with enhanced returns and features.',
    1000.01,
    10000.00,
    60,
    0.008, -- 0.8% daily
    2,
    '["Advanced trading signals", "Priority support", "Daily ROI payouts", "Portfolio analytics"]',
    '{"BTC": 35, "ETH": 35, "USDT": 30}'
),
(
    'Tier 3',
    'Advanced tier for serious investors.',
    10000.01,
    20000.00,
    90,
    0.012, -- 1.2% daily
    3,
    '["Premium trading signals", "24/7 support", "Daily ROI payouts", "Advanced analytics", "Risk management tools"]',
    '{"BTC": 30, "ETH": 40, "USDT": 30}'
),
(
    'Tier 4',
    'Professional tier with high returns.',
    20000.01,
    50000.00,
    120,
    0.015, -- 1.5% daily
    4,
    '["VIP trading signals", "Dedicated account manager", "Daily ROI payouts", "Custom analytics", "API access", "Lower fees"]',
    '{"BTC": 25, "ETH": 45, "USDT": 30}'
),
(
    'Tier 5',
    'Elite tier for maximum returns and exclusive benefits.',
    50000.01,
    10000000.00,
    180,
    0.02, -- 2.0% daily
    5,
    '["Exclusive signals", "Personal advisor", "Daily ROI payouts", "Custom strategies", "Priority API", "Zero fees", "Exclusive events"]',
    '{"BTC": 20, "ETH": 50, "USDT": 30}'
)
ON CONFLICT (name) DO NOTHING;

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER handle_investment_tiers_updated_at
    BEFORE UPDATE ON public.investment_tiers
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON public.investment_tiers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.investment_tiers TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.investment_tiers_id_seq TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.investment_tiers_id_seq TO service_role;
